### ISSUE TITLE
 the config file does not exist and I do not know what are the values ​​that I have to put

### ISSUE THREAD

**Issue by SimonLopezJara** [Asgarrrr/Luna#15]

**Comment by Asgarrrr** [comment]
Good evening, sorry, during a recent change, it was deleted, I put it back !

**Comment by SimonLopezJara** [comment]
What do I have to put in CLIENT_SECRET?

**Comment by Asgarrrr** [comment]
<img width="252" alt="Capture d’écran 2021-02-18 à 19 29 44" src="https://user-images.githubusercontent.com/36574651/108404021-a9028780-721f-11eb-97a6-fb289cc7269f.png">

**Comment by SimonLopezJara** [comment]
O:

**Comment by Asgarrrr** [comment]
I'm sorry for the inconvenience, I'm going to redo the doc and simplify everything soon ! ;3
