### ISSUE TITLE
DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by friendlymaninthisworld** [Asgarrrr/Luna#18]
DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/user/Documents/Luna-master/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push (/home/user/Documents/Luna-master/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/804408907354734682/messages',
  code: 50006,
  httpStatus: 400
}

This is fairly common

**Comment by Asgarrrr** [comment]
Mhhh You would have more details on how it happens  ?

**Comment by friendlymaninthisworld** [comment]
Oh, I was trying to find out what happens as well. This mostly happens when my friends and I type regularly. However, I searched in most scripts to see that maybe the bot was sending an empty embed or something. I think this happens because I don't use a prefix, but I doubt that.

**Comment by Asgarrrr** [comment]
I've never had this problem until now :/

**Comment by friendlymaninthisworld** [comment]
lol damn this is weird...
I'm going to trouble shoot a bit more. Just to see if it's something on my side.

**Comment by Asgarrrr** [comment]
Nice, maybe look at the level of the bot's permits? When you use too much a command, a message is sent with the cooldown, maybe that ?

**Comment by friendlymaninthisworld** [comment]
I think you're on the right track, this only happens if you spam or if multiple people are talking at the same time. 
However, I did a bit of searching and I narrowed it down to the events folder. (or more specifically messages.js)

**Comment by friendlymaninthisworld** [comment]
I also found a quick and dirty way:

delete this line in Luna.js 

process.on("unhandledRejection", (err) => {
    console.error(err);
});

**Comment by Asgarrrr** [comment]
Unfortunately, no longer seeing an error does not correct it ;(

**Comment by friendlymaninthisworld** [comment]
I mean your code does work, it's just a warning I get in the terminal

**Comment by Asgarrrr** [comment]
Haha I know ;3

**Comment by friendlymaninthisworld** [comment]
What is "setlog.js" supposed to do? 
becuase: TypeError: this.client.resolveChannel is not a function
it's the same problem as the avatar and unban stuff

**Comment by Asgarrrr** [comment]
Rhaaa x) "Je suis débile"

**Comment by Asgarrrr** [comment]
Oui, je le suis ;3

**Comment by Asgarrrr** [comment]
Et merci, vous me faites découvrir de nouveaux problèmes !

**Comment by friendlymaninthisworld** [comment]
C'est bon,
je n'aime pas française parce qu je travaille en anglais

**Comment by friendlymaninthisworld** [comment]
> Et merci, vous me faites découvrir de nouveaux problèmes !

merci

**Comment by Asgarrrr** [comment]
I can continue in English ;3

**Comment by friendlymaninthisworld** [comment]
Wait are you updating the git hub respiratory or are you updating your personal?

> I can continue in English ;3

thanks lol

**Comment by friendlymaninthisworld** [comment]
> Et merci, vous me faites découvrir de nouveaux problèmes !

I wasn't called "the problem child" by parents for nothing... ;-;

**Comment by Asgarrrr** [comment]
There I work locally, and as I finish (soon) PUSH!

**Comment by friendlymaninthisworld** [comment]
Oh, sweet! I'll wait for the next release then.

**Comment by Asgarrrr** [comment]
HOP

**Comment by friendlymaninthisworld** [comment]
Hey, did you find a fix to the problem yet?

**Comment by Asgarrrr** [comment]
Hello! As far as I don't have the problem on my side, I confess that I don't :( I'm doing a big cleanup and start again on a good base, I have work on the side that eats me up all my time :(

**Comment by friendlymaninthisworld** [comment]
I'm sorry for bothering you when you're so busy. I'm not too good at programming myself, but I really like the notes you place in the code so I use it to learn. I could heard you're working locally, could you update the respiratory?
