### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mistik** [Asgarrrr/Luna#25]
Hi 

Is there any plans to add documentation?

It would be nice to have a list of all commands and also how the dashboard works

**Comment by Mistik** [comment]
Also is there a support server?

**Comment by Asgarrrr** [comment]
Hi ! 

Luna is an ongoing project, but I thank you for your interest. A detailed documentation will be available soon!  - A Discord server exists yes, I will add it soon to the README.md

**Comment by Mistik** [comment]
> Hi !
> 
> Luna is an ongoing project, but I thank you for your interest. A detailed documentation will be available soon! - A Discord server exists yes, I will add it soon to the README.md

Ok thanks, please send it
