### ISSUE TITLE
Bot "impossessing" himself of the profile picture

### ISSUE THREAD

**Issue by paolosasso** [Asgarrrr/Luna#28]
Every time I start it up, he changes the profile pic

**Comment by Asgarrrr** [comment]
Hello, 

If you want to use a custom profile picture, I advise you to go to 
```
Events/ready.js
```

And delete lines 44 to 47 ( these lines :)
```
client.user.setAvatar("resources/Assets/Faces/Icon.png")
   .catch((error) => {
      console.error(error);
   });
```

**Comment by paolosasso** [comment]
Thanks!!!

Il dom 23 mag 2021, 13:13 Jérémy Caruelle ***@***.***> ha
scritto:
